# Generated by Django 4.2.8 on 2023-12-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="temporary_token",
            field=models.CharField(null=True),
        ),
    ]
