# Generated by Django 4.2.8 on 2023-12-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userprofile_temporary_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="temporary_token",
            field=models.TextField(null=True, unique=True),
        ),
    ]
