# Generated by Django 4.2.8 on 2023-12-28 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_temporary_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sso_user_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="token_expiry",
        ),
    ]
