# Generated by Django 4.2.8 on 2023-12-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0046_drug_url_field"),
        ("users", "0004_remove_userprofile_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="pages.specialty",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="temporary_token",
            field=models.CharField(null=True, unique=True),
        ),
    ]
