# Generated by Django 4.2.8 on 2023-12-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userprofile_temporary_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="temporary_token",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
