# Generated by Django 4.2.8 on 2023-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_specialty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="saved_content",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
