# Generated by Django 4.2.8 on 2024-03-06 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0002_rename_description_practicum_desription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prtest",
            old_name="question",
            new_name="questions",
        ),
    ]
