# Generated by Django 4.2.8 on 2024-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0005_practicum_screenbutton_screenimageblock_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prtest",
            old_name="questions",
            new_name="question",
        ),
    ]
