# Generated by Django 4.2.8 on 2024-03-06 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0006_rename_questions_prtest_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopUpPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PopUpBlockId", models.IntegerField()),
                ("title", models.CharField()),
                ("text", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
