# Generated by Django 4.2.8 on 2024-03-06 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0007_popuppoint"),
        ("practics", "0007_rename_desription_practicum_description"),
    ]

    operations = []
