# Generated by Django 4.2.8 on 2024-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0008_merge_20240306_1825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicum",
            name="priority",
            field=models.IntegerField(
                default=50,
                help_text="Целое число от 1 до 50 включительно.",
                verbose_name="Приоритет",
            ),
        ),
    ]
