# Generated by Django 4.2.8 on 2024-03-07 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practics", "0010_alter_screens_literature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screens",
            name="approvals_and_decodings",
            field=ckeditor.fields.RichTextField(
                verbose_name="Номер одобрения и расшифровка"
            ),
        ),
        migrations.AlterField(
            model_name="screens",
            name="leterature_approvals_and_decodings",
            field=ckeditor.fields.RichTextField(
                verbose_name="Номер одобрения и расшифровка для списка литературы"
            ),
        ),
        migrations.AlterField(
            model_name="screens",
            name="literature",
            field=models.CharField(verbose_name="список литературы"),
        ),
    ]
