version: "3.7"

services:

  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd33
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  kernel:
    build: ./kernel
    volumes:
      - ./kernel:/app
    env_file:
      - ./kernel/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    depends_on:
      - nuxt
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    restart: always

  nuxt:
    build: ./frontend
    expose:
      - '8080:8080'
    restart: always
