version: "3.7"

services:

  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd33
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  kernel:
    build: ./kernel
    volumes:
      - ./kernel:/app
      - ./kernel/static:/app/static
    env_file:
      - ./kernel/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nuxt:
    build: ./frontend
    volumes:
      - './frontend:/workdir'
    expose:
      - '3000:3000'
    restart: always

  nginx:
    image: staticfloat/nginx-certbot
    depends_on:
      - kernel
    volumes:
      - ./kernel/static:/var/www/html/static
      - ./kernel/media:/var/www/html/media
      - ./frontend/.nuxt:/var/www/html/static
      - ./frontend/.output:/var/www/html/static
      - ./nginx:/etc/nginx/user.conf.d
      - letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    environment:
      CERTBOT_EMAIL: anton.s@aliensource.org
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped


volumes:
  static:
  letsencrypt:
  www-html:


