version: "3.7"

services:

  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd33
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  kernel:
    build: ./kernel
    volumes:
      - ./kernel:/app
    env_file:
      - ./kernel/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nuxt:
    build: ./frontend
    expose:
      - '3000:3000'
    restart: always

  nginx:
      image: nginx:1.19.8-alpine
      depends_on:
        - nuxt
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./kernel/static:/var/www/html/static
        - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
        - ./data/etc-letsencrypt/:/etc/letsencrypt
        - www-html:/var/www/html
  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./data/etc-letsencrypt:/etc/letsencrypt
        - ./kernel/static:/var/www/html/static
        - www-html:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --email \
        maccre.a@yandex.ru --agree-tos --no-eff-email -d astraportal.dev-demo.online

volumes:
  pg_data:
  static:
  etc-letsencrypt:
  www-html:
