version: "3.7"

services:

  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd33
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  kernel:
    build: ./kernel
    volumes:
      - ./kernel:/app
    env_file:
      - ./kernel/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nuxt:
    build: ./frontend
    expose:
      - '3000:3000'
    restart: always

  nginx:
    build: ./nginx
    depends_on:
      - nuxt
    volumes:
      - ./kernel/static:/static
      - ./kernel/media:/media
    ports:
      - '80:80'
    restart: always
