version: "3.7"

services:

  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd33
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  kernel:
    build: ./kernel
    volumes:
      - ./kernel:/app
    env_file:
      - ./kernel/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nuxt:
    build: ./frontend
    expose:
      - '3000:3000'
    restart: always


  nginx:
    image: nginx:latest
    depends_on:
      - kernel
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro


  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  pg_data:
  static:
  etc-letsencrypt:
  www-html:
