version: '3.7'

services:
  db:
    image: 'postgres:12.4'
    shm_size: '256m'
    restart: on-failure
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: db
      POSTGRES_PASSWORD: Passw0rd33
  kernel:
    user: vscode
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '..:/workspace:cached'
    ports:
      - '5000:5000'
    command: sleep infinity
