# Generated by Django 4.2.8 on 2023-12-29 02:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_name",
                    models.CharField(max_length=1024, verbose_name="Заголовок"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="article_covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "short_description",
                    ckeditor.fields.RichTextField(verbose_name="Краткое описание"),
                ),
                (
                    "final_content",
                    ckeditor.fields.RichTextField(verbose_name="Заключение"),
                ),
                (
                    "access_number",
                    ckeditor.fields.RichTextField(
                        verbose_name="Поле для добавления расшифровок и номеров одобрения"
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        blank=True,
                        choices=[("статья", "Статья"), ("инновация", "Инновация")],
                        max_length=255,
                        verbose_name="Тип статьи",
                    ),
                ),
                (
                    "information",
                    ckeditor.fields.RichTextField(
                        verbose_name="текстовый блок для ввода инфы о статьи на разводящей станице статей"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название препарата"),
                ),
                (
                    "brief_info",
                    models.TextField(verbose_name="Краткое описание препарата"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="drug_images/", verbose_name="Изображение препарата"
                    ),
                ),
                (
                    "approvals_and_decodings",
                    ckeditor.fields.RichTextField(
                        verbose_name="Расшифровки и номера одобрения"
                    ),
                ),
                (
                    "url_field",
                    models.URLField(
                        null=True, verbose_name="Ссылка на интрукцию в PDF"
                    ),
                ),
                (
                    "application_practice_articles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="application_practice_articles",
                        to="pages.articles",
                        verbose_name="Статьи в практике применения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Препарат",
                "verbose_name_plural": "Препараты",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=255, verbose_name="Дата мероприятия"),
                ),
                ("cover", models.ImageField(upload_to="event_covers/")),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание мероприятия"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="SavedByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название специальности",
                    ),
                ),
                ("image", models.ImageField(upload_to="specialty_images/")),
                ("pro", models.CharField(null=True, verbose_name="PRO-")),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="VideoLectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_article",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "conspect",
                    ckeditor.fields.RichTextField(verbose_name="Конспект видео"),
                ),
                (
                    "video",
                    models.FileField(upload_to="video_lectures/", verbose_name="Видео"),
                ),
                (
                    "video_cover",
                    models.ImageField(
                        upload_to="video_covers/", verbose_name="Обложка видео"
                    ),
                ),
                (
                    "access_number",
                    ckeditor.fields.RichTextField(
                        verbose_name="Поле для добавления расшифровок и номеров одобрения"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("видеолекция", "Видеолекция"), ("кейс", "Кейс")],
                        max_length=255,
                        verbose_name="Поле для выбора типа контента",
                    ),
                ),
                (
                    "drug",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.drug",
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "speciality",
                    models.ManyToManyField(
                        to="pages.specialty", verbose_name="Специальность"
                    ),
                ),
                (
                    "video_recomendations",
                    models.ManyToManyField(
                        blank=True, null=True, to="pages.videolectures"
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="story_avatars/")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="story_videos/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="story_covers/"),
                ),
                ("link_to_page", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "specialties",
                    models.ManyToManyField(blank=True, null=True, to="pages.specialty"),
                ),
            ],
            options={
                "verbose_name": "Истории",
                "verbose_name_plural": "Истории",
            },
        ),
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        help_text="Поддерживаются изображения и SVG",
                        upload_to="icon_files/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icons_set",
                        to="pages.drug",
                        verbose_name="Препарат",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(verbose_name="Текст")),
                (
                    "order",
                    models.PositiveBigIntegerField(verbose_name="Порядковый номер"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FAQ",
                        to="pages.drug",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="application_practice_videos",
            field=models.ManyToManyField(
                blank=True,
                related_name="application_practice_videos",
                to="pages.videolectures",
                verbose_name="Видео в практике применения",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="faq",
            field=models.ManyToManyField(
                blank=True, related_name="drugs", to="pages.drugfaq", verbose_name="FAQ"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="icons",
            field=models.ManyToManyField(
                blank=True, related_name="drugs", to="pages.icon", verbose_name="Иконки"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="speciality",
            field=models.ManyToManyField(
                to="pages.specialty", verbose_name="Специальность"
            ),
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("quote", "Цитата"),
                            ("image", "Изображение"),
                            ("text_with_image", "Текст с изображением"),
                        ],
                        max_length=16,
                        verbose_name="Тип контента",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content_block_images/"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="pages.articles",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="articles",
            name="drug",
            field=models.ManyToManyField(
                blank=True, to="pages.drug", verbose_name="Препараты"
            ),
        ),
        migrations.AddField(
            model_name="articles",
            name="speciality",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="pages.specialty",
                verbose_name="Специальности",
            ),
        ),
    ]
