# Generated by Django 4.2.8 on 2023-12-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название препарата"),
                ),
                (
                    "brief_info",
                    models.TextField(verbose_name="Краткое описание препарата"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="drug_images/", verbose_name="Изображение препарата"
                    ),
                ),
                (
                    "icoins",
                    models.ImageField(upload_to="drug_icons/", verbose_name="Иконки"),
                ),
                (
                    "instruction_points",
                    models.TextField(verbose_name="Список названий пунктов инструкции"),
                ),
                (
                    "instruction_text",
                    models.TextField(verbose_name="Текст пункта инструкции"),
                ),
                (
                    "application_practice",
                    models.TextField(verbose_name="Практика применения"),
                ),
                (
                    "approvals_and_decodings",
                    models.TextField(verbose_name="Расшифровки и номера одобрения"),
                ),
            ],
            options={
                "verbose_name": "Препараты",
                "verbose_name_plural": "Препараты",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=255, verbose_name="Дата мероприятия"),
                ),
                ("cover", models.ImageField(upload_to="event_covers/")),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="SavedByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название специальности",
                    ),
                ),
                ("image", models.ImageField(upload_to="specialty_images/")),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="VideoLectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_article",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                ("conspect", models.TextField(verbose_name="Конспект видео")),
                ("video", models.FileField(upload_to="video_lectures/")),
                (
                    "video_cover",
                    models.ImageField(
                        upload_to="video_covers/", verbose_name="Обложка видео"
                    ),
                ),
                (
                    "access_number",
                    models.CharField(
                        max_length=255,
                        verbose_name="Поле для добавления расшифровок и номеров одобрения",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        max_length=255,
                        verbose_name="поле для выбора типа контента - видеолекции или видео кейс",
                    ),
                ),
                (
                    "drug",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.drug"
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.specialty",
                    ),
                ),
                (
                    "video_recomendations",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "video_article": models.F(
                                "video_recomendations__video_article"
                            )
                        },
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.videolectures",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="story_avatars/")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="story_videos/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="story_covers/"),
                ),
                ("link_to_page", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("specialties", models.ManyToManyField(to="pages.specialty")),
            ],
            options={
                "verbose_name": "Истории",
                "verbose_name_plural": "Истории",
            },
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_name",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Заголовок"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="article_covers/"
                    ),
                ),
                ("article_text", models.TextField(blank=True)),
                ("quote", models.TextField(blank=True)),
                (
                    "quote_image",
                    models.ImageField(blank=True, null=True, upload_to="quote_images/"),
                ),
                ("drug_url", models.URLField(blank=True, null=True)),
                ("final_content", models.CharField(blank=True, max_length=255)),
                (
                    "access_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Поле для добавления расшифровок и номеров одобрения",
                    ),
                ),
                ("article_type", models.CharField(blank=True, max_length=255)),
                (
                    "drug",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="pages.drug"
                    ),
                ),
                (
                    "speciality",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="pages.specialty"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
