# Generated by Django 4.2.8 on 2023-12-15 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="description",
        ),
    ]
