# Generated by Django 4.2.8 on 2024-03-06 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="name",
            new_name="namee",
        ),
    ]
