# Generated by Django 4.2.8 on 2023-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="article_type",
            field=models.CharField(
                blank=True,
                choices=[("статья", "Статья"), ("инновация", "Инновация")],
                max_length=255,
            ),
        ),
    ]
