# Generated by Django 4.2.8 on 2023-12-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videolectures",
            name="drug",
        ),
        migrations.AddField(
            model_name="videolectures",
            name="drug",
            field=models.ManyToManyField(
                blank=True, null=True, to="pages.drug", verbose_name="Препарат"
            ),
        ),
    ]
