# Generated by Django 4.2.8 on 2023-12-29 06:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_remove_videolectures_drug_videolectures_drug"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="first_abzac",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Первый абзац"),
        ),
    ]
