# Generated by Django 4.2.8 on 2023-12-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0002_remove_specialty_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="story_avatars/")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="story_videos/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="story_covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "link_to_page",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на страницу"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Статус отображения"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        to="pages.specialty", verbose_name="Специальности"
                    ),
                ),
            ],
        ),
    ]
