# Generated by Django 4.2.8 on 2023-12-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_articles_article_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolectures",
            name="content_type",
            field=models.CharField(
                choices=[("видеолекция", "Видеолекции"), ("кейс", "Кейс")],
                max_length=255,
                verbose_name="поле для выбора типа контента",
            ),
        ),
    ]
