# Generated by Django 4.2.8 on 2023-12-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название препарата"),
                ),
                (
                    "brief_info",
                    models.TextField(verbose_name="Краткое описание препарата"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="drug_images/", verbose_name="Изображение препарата"
                    ),
                ),
                (
                    "icoins",
                    models.ImageField(upload_to="drug_icons/", verbose_name="Иконки"),
                ),
                (
                    "instruction_points",
                    models.TextField(verbose_name="Список названий пунктов инструкции"),
                ),
                (
                    "instruction_text",
                    models.TextField(verbose_name="Текст пункта инструкции"),
                ),
                (
                    "application_practice",
                    models.TextField(verbose_name="Практика применения"),
                ),
                (
                    "approvals_and_decodings",
                    models.TextField(verbose_name="Расшифровки и номера одобрения"),
                ),
            ],
            options={
                "verbose_name": "Препараты",
                "verbose_name_plural": "Препараты",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date",
                    models.CharField(max_length=255, verbose_name="Дата мероприятия"),
                ),
                ("cover", models.ImageField(upload_to="event_covers/")),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="SavedByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_data", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "Истории", "verbose_name_plural": "Истории"},
        ),
        migrations.RemoveField(
            model_name="story",
            name="author",
        ),
        migrations.AlterField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="story_covers/"),
        ),
        migrations.AlterField(
            model_name="story",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="link_to_page",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="story",
            name="specialties",
            field=models.ManyToManyField(to="pages.specialty"),
        ),
        migrations.AlterField(
            model_name="story",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="story_videos/"),
        ),
        migrations.CreateModel(
            name="VideoLectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_article",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                ("conspect", models.TextField(verbose_name="Конспект видео")),
                ("video", models.FileField(upload_to="video_lectures/")),
                (
                    "video_cover",
                    models.ImageField(
                        upload_to="video_covers/", verbose_name="Обложка видео"
                    ),
                ),
                (
                    "access_number",
                    models.CharField(
                        max_length=255,
                        verbose_name="Поле для добавления расшифровок и номеров одобрения",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        max_length=255,
                        verbose_name="поле для выбора типа контента - видеолекции или видео кейс",
                    ),
                ),
                (
                    "drug",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.drug"
                    ),
                ),
                (
                    "saved_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.savedbyuser",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.specialty",
                    ),
                ),
                (
                    "video_recomendations",
                    models.ForeignKey(
                        limit_choices_to={
                            "video_article": models.F(
                                "video_recomendations__video_article"
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.videolectures",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
        migrations.AddField(
            model_name="drug",
            name="saved_data",
            field=models.ManyToManyField(to="pages.savedbyuser"),
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=255)),
                ("cover", models.ImageField(upload_to="article_covers/")),
                ("article_text", models.TextField()),
                ("quote", models.TextField()),
                ("quote_image", models.ImageField(upload_to="quote_images/")),
                ("drug_url", models.URLField()),
                ("final_content", models.CharField(max_length=255)),
                (
                    "access_number",
                    models.CharField(
                        max_length=255,
                        verbose_name="Поле для добавления расшифровок и номеров одобрения",
                    ),
                ),
                ("article_type", models.CharField(max_length=255)),
                (
                    "drug",
                    models.ManyToManyField(related_name="articles", to="pages.drug"),
                ),
                (
                    "saved_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.savedbyuser",
                    ),
                ),
                (
                    "speciality",
                    models.ManyToManyField(
                        related_name="articles", to="pages.specialty"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AddField(
            model_name="story",
            name="saved_data",
            field=models.ManyToManyField(to="pages.savedbyuser"),
        ),
    ]
