# Generated by Django 4.2.8 on 2023-12-29 06:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_articles_first_abzac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="first_abzac",
            field=ckeditor.fields.RichTextField(verbose_name="Первый абзац"),
        ),
    ]
