# Generated by Django 4.2.8 on 2023-12-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_alter_articles_first_abzac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="link_to_page",
            field=models.URLField(null=True),
        ),
    ]
