# Generated by Django 4.2.8 on 2023-12-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_alter_videolectures_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolectures",
            name="drug",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.drug",
            ),
        ),
    ]
