# Generated by Django 4.2.8 on 2023-12-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_drug_events_savedbyuser_alter_specialty_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="saved_data",
            field=models.ManyToManyField(null=True, to="pages.savedbyuser"),
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="saved_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.savedbyuser",
            ),
        ),
    ]
