# Generated by Django 4.2.8 on 2023-12-26 11:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_videolectures_drug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="icoins",
            field=jsonfield.fields.JSONField(
                blank=True, null=True, verbose_name="Иконки"
            ),
        ),
    ]
