# Generated by Django 4.2.8 on 2023-12-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_drug_saved_data_alter_videolectures_saved_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="saved_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.savedbyuser",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="saved_data",
            field=models.ManyToManyField(null=True, to="pages.savedbyuser"),
        ),
    ]
