# Generated by Django 4.2.8 on 2023-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_story_link_to_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="link_to_page",
            field=models.URLField(blank=True, null=True),
        ),
    ]
