# Generated by Django 4.2.8 on 2023-12-26 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_drug_icoins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="article_text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
