# Generated by Django 4.2.8 on 2023-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_articles_saved_data_alter_story_saved_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название мероприятия"),
        ),
    ]
