# Generated by Django 4.2.8 on 2023-12-21 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_events_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
