# Generated by Django 4.2.8 on 2023-12-29 20:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_events_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageApproveNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    ckeditor.fields.RichTextField(verbose_name="Номер одобрения"),
                ),
            ],
            options={
                "verbose_name": "Главная страница",
            },
        ),
        migrations.AlterField(
            model_name="drug",
            name="url_field",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на интрукцию в PDF"
            ),
        ),
    ]
