# Generated by Django 4.2.8 on 2023-12-26 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_articles_article_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="article_name",
            field=models.CharField(max_length=1024, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="article_text",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="articles",
            name="quote",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
