# Generated by Django 4.2.8 on 2023-12-21 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_events_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="saved_data",
        ),
    ]
