# Generated by Django 4.2.8 on 2023-12-29 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_mainpageapprovenumber_alter_drug_url_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpageapprovenumber",
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
    ]
