# Generated by Django 4.2.8 on 2023-12-21 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_remove_story_saved_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="saved_data",
        ),
    ]
