# Generated by Django 4.2.8 on 2023-12-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_remove_articles_drug_remove_articles_drug_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="article",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="article",
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[("quote", "Цитата"), ("image", "Изображение")],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="pages.articles",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.image",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.quote",
                    ),
                ),
            ],
        ),
    ]
