# Generated by Django 4.2.8 on 2023-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_remove_articles_saved_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="saved_data",
        ),
        migrations.RemoveField(
            model_name="videolectures",
            name="saved_data",
        ),
    ]
