# Generated by Django 4.2.8 on 2023-12-26 23:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_remove_image_article_remove_quote_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="article_text",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="block_type",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="image",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="quote",
        ),
        migrations.AddField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("quote", "Цитата"),
                    ("image", "Изображение"),
                ],
                default="text",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
