# Generated by Django 4.2.8 on 2023-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_remove_drug_saved_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название специальности"
            ),
        ),
    ]
