# Generated by Django 4.2.8 on 2023-12-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_remove_articles_article_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("quote", "Цитата"),
                    ("image", "Изображение"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
