# Generated by Django 4.2.8 on 2023-12-26 23:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_alter_contentblock_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentblock",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
