# Generated by Django 4.2.8 on 2023-12-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_alter_videolectures_video_recomendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolectures",
            name="video_recomendations",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "video_article": models.F("video_recomendations__video_article")
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.videolectures",
            ),
        ),
    ]
