# Generated by Django 4.2.8 on 2023-12-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_alter_contentblock_options_alter_contentblock_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentblock",
            options={},
        ),
        migrations.AddField(
            model_name="contentblock",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="content_block_images/"
            ),
        ),
    ]
