# Generated by Django 4.2.8 on 2023-12-26 23:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_alter_contentblock_options_contentblock_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="access_number",
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name="Поле для добавления расшифровок и номеров одобрения",
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article_covers/",
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="final_content",
            field=ckeditor.fields.RichTextField(verbose_name="Заключение"),
        ),
    ]
