# Generated by Django 4.2.8 on 2023-12-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_alter_articles_access_number_alter_articles_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="article_type",
            field=models.CharField(
                blank=True,
                choices=[("статья", "Статья"), ("инновация", "Инновация")],
                max_length=255,
                verbose_name="Тип статьи",
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="speciality",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="pages.specialty",
                verbose_name="Специальности",
            ),
        ),
    ]
