# Generated by Django 4.2.8 on 2023-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_alter_articles_article_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("quote", "Цитата"),
                    ("image", "Изображение"),
                    ("text_with_image", "Текст с картинкой"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
