# Generated by Django 4.2.8 on 2023-12-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_alter_contentblock_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("quote", "Цитата"),
                    ("image", "Изображение"),
                    ("text_with_image", "Текст с изображением"),
                ],
                max_length=16,
            ),
        ),
    ]
