# Generated by Django 4.2.8 on 2023-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_alter_contentblock_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="drug",
            field=models.ManyToManyField(
                blank=True, to="pages.drug", verbose_name="Препораты"
            ),
        ),
    ]
