# Generated by Django 4.2.8 on 2023-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0020_alter_contentblock_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="drug",
            field=models.ManyToManyField(
                blank=True, to="pages.drug", verbose_name="Препараты"
            ),
        ),
    ]
