# Generated by Django 4.2.8 on 2023-12-27 00:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_alter_articles_drug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="instruction_text",
            field=ckeditor.fields.RichTextField(verbose_name="Текст инструкции"),
        ),
    ]
