# Generated by Django 4.2.8 on 2023-12-27 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_alter_drug_instruction_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="application_practice",
            field=ckeditor.fields.RichTextField(verbose_name="Практика применения"),
        ),
        migrations.AlterField(
            model_name="drug",
            name="approvals_and_decodings",
            field=ckeditor.fields.RichTextField(
                verbose_name="Расшифровки и номера одобрения"
            ),
        ),
    ]
