# Generated by Django 4.2.8 on 2023-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0023_events_text_alter_drug_application_practice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
