# Generated by Django 4.2.8 on 2023-12-27 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0024_alter_events_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolectures",
            name="conspect",
            field=ckeditor.fields.RichTextField(verbose_name="Конспект видео"),
        ),
    ]
