# Generated by Django 4.2.8 on 2023-12-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0025_alter_videolectures_conspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolectures",
            name="content_type",
            field=models.CharField(
                choices=[("видеолекция", "Видеолекция"), ("кейс", "Кейс")],
                max_length=255,
                verbose_name="Поле для выбора типа контента",
            ),
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="drug",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.drug",
                verbose_name="Препарат",
            ),
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.specialty",
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="video",
            field=models.FileField(upload_to="video_lectures/", verbose_name="Видео"),
        ),
    ]
