# Generated by Django 4.2.8 on 2023-12-27 01:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0027_videolectures_short_sescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="access_number",
            field=ckeditor.fields.RichTextField(
                verbose_name="Поле для добавления расшифровок и номеров одобрения"
            ),
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="short_sescription",
            field=models.TextField(verbose_name="Краткое описание"),
        ),
    ]
