# Generated by Django 4.2.8 on 2023-12-27 01:18

from django.db import migrations, models
import pages.services.drugs_services


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_alter_articles_access_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="icoins",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="drug_images/",
                validators=[
                    pages.services.drugs_services.validate_svg,
                    pages.services.drugs_services.validate_max_4_files,
                ],
                verbose_name="Иконки",
            ),
        ),
    ]
