# Generated by Django 4.2.8 on 2023-12-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0029_alter_drug_icoins"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drug",
            options={"verbose_name": "Препарат", "verbose_name_plural": "Препараты"},
        ),
        migrations.RemoveField(
            model_name="drug",
            name="icoins",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="instruction_points",
        ),
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="icon_images/", verbose_name="Иконка"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icon_related",
                        to="pages.drug",
                        verbose_name="Препарат",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="icons",
            field=models.ManyToManyField(
                blank=True,
                related_name="drug_related",
                to="pages.icon",
                verbose_name="Иконки",
            ),
        ),
    ]
