# Generated by Django 4.2.8 on 2023-12-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0030_alter_drug_options_remove_drug_icoins_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="icon",
            name="image",
        ),
        migrations.AddField(
            model_name="icon",
            name="image_file",
            field=models.FileField(
                blank=True,
                help_text="Поддерживаются изображения и SVG",
                upload_to="icon_files/",
                verbose_name="Иконка",
            ),
        ),
        migrations.AddField(
            model_name="icon",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("svg", "SVG")],
                default="image",
                max_length=5,
                verbose_name="Тип изображения",
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="icons",
            field=models.ManyToManyField(
                blank=True, related_name="drugs", to="pages.icon", verbose_name="Иконки"
            ),
        ),
        migrations.AlterField(
            model_name="icon",
            name="drug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="icons_set",
                to="pages.drug",
                verbose_name="Препарат",
            ),
        ),
    ]
