# Generated by Django 4.2.8 on 2023-12-27 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0031_remove_icon_image_icon_image_file_icon_image_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="icon",
            name="image_type",
        ),
    ]
