# Generated by Django 4.2.8 on 2023-12-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0032_remove_icon_image_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="application_practice",
        ),
        migrations.AddField(
            model_name="drug",
            name="application_practice_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="application_practice_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
