# Generated by Django 4.2.8 on 2023-12-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0033_remove_drug_application_practice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="application_practice_id",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="application_practice_type",
        ),
        migrations.AddField(
            model_name="drug",
            name="application_practice_articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="application_practice_articles",
                to="pages.articles",
                verbose_name="Статьи в практике применения",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="application_practice_videos",
            field=models.ManyToManyField(
                blank=True,
                related_name="application_practice_videos",
                to="pages.videolectures",
                verbose_name="Видео в практике применения",
            ),
        ),
    ]
