# Generated by Django 4.2.8 on 2023-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0034_remove_drug_application_practice_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="specialties",
            field=models.ManyToManyField(blank=True, null=True, to="pages.specialty"),
        ),
    ]
