# Generated by Django 4.2.8 on 2023-12-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0035_alter_story_specialties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videolectures",
            old_name="short_sescription",
            new_name="short_description",
        ),
        migrations.AlterField(
            model_name="videolectures",
            name="video_recomendations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.videolectures",
            ),
        ),
    ]
