# Generated by Django 4.2.8 on 2023-12-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0037_alter_videolectures_access_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="pro",
            field=models.CharField(null=True, verbose_name="PRO-"),
        ),
    ]
