# Generated by Django 4.2.8 on 2023-12-28 04:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0039_articles_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="short_description",
            field=ckeditor.fields.RichTextField(verbose_name="Краткое описание"),
        ),
    ]
