# Generated by Django 4.2.8 on 2023-12-28 04:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0042_alter_articles_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="information",
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name="текстовый блок для ввода инфы о статьи на разводящей станице статей",
            ),
        ),
    ]
