# Generated by Django 4.2.8 on 2023-12-28 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0043_articles_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="information",
            field=ckeditor.fields.RichTextField(
                verbose_name="текстовый блок для ввода инфы о статьи на разводящей станице статей"
            ),
        ),
    ]
