# Generated by Django 4.2.8 on 2023-12-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0044_alter_articles_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="speciality",
            field=models.ManyToManyField(
                to="pages.specialty", verbose_name="Специальность"
            ),
        ),
        migrations.RemoveField(
            model_name="videolectures",
            name="speciality",
        ),
        migrations.RemoveField(
            model_name="videolectures",
            name="video_recomendations",
        ),
        migrations.AddField(
            model_name="videolectures",
            name="speciality",
            field=models.ManyToManyField(
                to="pages.specialty", verbose_name="Специальность"
            ),
        ),
        migrations.AddField(
            model_name="videolectures",
            name="video_recomendations",
            field=models.ManyToManyField(
                blank=True, null=True, to="pages.videolectures"
            ),
        ),
    ]
