# Generated by Django 4.2.8 on 2023-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0045_drug_speciality_remove_videolectures_speciality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="url_field",
            field=models.URLField(null=True, verbose_name="Ссылка на интрукцию в PDF"),
        ),
    ]
