# Generated by Django 4.2.8 on 2023-12-28 21:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0046_drug_url_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="instruction_text",
        ),
        migrations.CreateModel(
            name="drug_FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(verbose_name="Текст")),
                ("order", models.PositiveBigIntegerField()),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FAQ",
                        to="pages.drug",
                    ),
                ),
            ],
        ),
    ]
