# Generated by Django 4.2.8 on 2023-12-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0047_remove_drug_instruction_text_drug_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_faq",
            name="order",
            field=models.PositiveBigIntegerField(verbose_name="Порядковый номер"),
        ),
    ]
